<%@ Page Language="C#" MasterPageFile="~/BasicForm/BasicForm.master" AutoEventWireup="true" CodeFile="Exercise.aspx.cs" Inherits="Exercise_Exercise" Title="課堂練習"  %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphAdvancedProcessArea" runat="Server">
    <asp:ScriptManagerProxy ID="_proxy" runat="server">
    </asp:ScriptManagerProxy>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="cphContentArea" Runat="Server">
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="../Scripts/jquery-1.6.4.min.js" "></script>
    <!--Reference the SignalR library. -->
    <script src="../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src='<%: ResolveClientUrl("~/signalr/hubs") %>'></script>
     <script type="text/javascript">
         $(function () {
             var userID = $('#ctl00_cphContentArea_HUserID').val();
             var groupID = $('#ctl00_cphContentArea_HTempGroupID').val();
                // Declare a proxy to reference the hub.
                var chat = $.connection.chatHub;
                // Create a function that the hub can call to broadcast messages.
                chat.client.broadcastMessage = function (name, message) {
                    // Html encode display name and message.
                    //var encodedName = $('<div />').text(name).html();
                    //var encodedMsg = $('<div />').text(message).html();
                    // Add the message to the page.
                    //$('#discussion').append('<li><strong>' + name
                    //    + '</strong>:&nbsp;&nbsp;' + message + '</li>');
                    //特殊事件藉由"-"來區分是否為特殊指令(ex:開啟視窗)
                    var messageArray = message.split("#");
                    if (messageArray.length >1 )
                    switch (messageArray[0]) {
                        //通知小組成員開啟考卷
                        case "OpenWindows":
                            //推播給同組成員開啟考卷 不包含自己
                            if (userID != name) {
                                window.open(messageArray[1]);
                            }
                            break;
                        default:
                            break;
                    }
                };
                // Start the connection.
                $.connection.hub.start().done(function () {
                    //連線設定GroupID
                    chat.server.group(groupID);
                    //當傳遞事件發生時
                    $('#sendmessage').click(function () {
                        // Call the Send method on the hub.
                        chat.server.send(groupID, userID, $('#message').val());
                    });
                });
            });
    </script>
    <script type="text/javascript">
        //通知教師作答時間快到是否增加作答時間
        function TimeConfirm(cExerciseID, cEndTime, cGroupID, cExerciseNum) {
            if (confirm("第" + cExerciseNum + "份題目作答時間只剩2分鐘，是否增加作答時間?")) {
                //開啟修改作答時間視窗
                window.open("ModifyExerciseTime.aspx?cExerciseID=" + cExerciseID + "&cEndTime=" + cEndTime + "&cGroupID=" + cGroupID ,'OpenModifyExerciseTime', 'width=380px, height=300px');
            }
        }
    </script>
    <asp:UpdatePanel ID="upalExerciseState" runat="server">
        <ContentTemplate>
            <asp:Timer ID="timExerciseState" runat="server" ontick="timExerciseState_Tick" Interval="1500">
            </asp:Timer>
            <table ID="tbExDetialState" runat="server" align="center" 
                style="border-collapse:collapse; font-size: large;" cellpadding="10">
            </table>
        </ContentTemplate>
    </asp:UpdatePanel>
    <br />
    <asp:UpdatePanel ID="upalExerciseCond" runat="server">
        <ContentTemplate>
            <asp:Timer ID="timExerciseCond" runat="server" ontick="timExerciseCond_Tick" Interval="1000">
            </asp:Timer>
            <table id="tbExCondALL" runat="server" align="center" style="">
            <tr><td>
            <table ID="tbExCond" runat="server" align="center" style="font-size: large">
                <tr>
                    <td align="center">
                        <asp:Label ID="lbExerciseTitle" runat="server" Font-Bold="True" ForeColor="Red" Font-Size="X-Large"></asp:Label>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lbExceptAns" runat="server" Text="&nbsp;&nbsp;&nbsp;應作答人數: 0 人"></asp:Label> |
                        <asp:Label ID="lbActualAns" runat="server" Text="<img src='../App_Themes/general/images/actual_ans.png' width='25px' />已作答人數: 0 人" ForeColor="Blue"></asp:Label>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lbNotAns" runat="server" Text="<img src='../App_Themes/general/images/not_ans.png' width='25px' />未作答人數: 0 人" ForeColor="Brown"></asp:Label> |
                        <asp:Label ID="lbAbsenceAtt" runat="server" Text="<img src='../App_Themes/general/images/offline.png' width='25px' />未到人數: 0 人" ForeColor="Red"></asp:Label>
                    </td>
                </tr>
            </table>
            <table ID="tbExCondGroup" runat="server" align="center" style="font-size: large">
                <tr>
                    <td align="center">
                        <asp:Label ID="lbExerciseTitleGroup" runat="server" Font-Bold="True" ForeColor="Red" Font-Size="X-Large"></asp:Label>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lbExceptAnsGroup" runat="server" Text="&nbsp;&nbsp;&nbsp;應作答小組: 0 組"></asp:Label> |
                        <asp:Label ID="lbActualAnsGroup" runat="server" Text="<img src='../App_Themes/general/images/actual_ans.png' width='25px' />已作答人數: 0 組" ForeColor="Blue"></asp:Label> |
                        <asp:Label ID="lbNotAnsGroup" runat="server" Text="<img src='../App_Themes/general/images/not_ans.png' width='25px' />未作答人數: 0 組" ForeColor="Brown"></asp:Label>
                    </td>
                </tr>
            </table>
            <table ID="tbTimeRemnant" runat="server" style="font-size: large" align="center" cellpadding="10" visible="false">
                <tr>
                    <td>
                        <asp:Label id="lbTimeRemnantTitle" runat="server" Text="作答剩餘時間:" />
                    </td>
                    <td>
                        <asp:Label id="lbTimeRemnant" runat="server" Text="00'00'00" ForeColor="Red" />
                    </td>
                    <td>
                        <asp:Button id="btnModifyTime" runat="server" Text="修改作答時間" Font-Size="medium" onClick="btnModifyTime_Click" />
                    </td>
                </tr>
            </table>
            <table align="center" cellpadding="10">
                <tr>
                    <td>
                        <asp:Button ID="btnShowExerciseCond" runat="server"
                            CssClass="ORCS_button_control" Font-Size="Medium" Width="260" Text="目前不允許學生觀看作答狀況"
                            OnClick="btnShowExerciseCond_Click" />&nbsp;&nbsp;&nbsp;&nbsp;
                       <asp:Button ID="btnShowExerciseAns" runat="server"
                           CssClass="ORCS_button_control" Font-Size="Medium" Width="260" Text="目前不允許學生互相觀看答案"
                           OnClick="btnShowExerciseAns_Click" />
                    </td>
                </tr>
            </table>
            <br />
            <table ID="tbExDetialCond" runat="server" align="center" 
                style="border-collapse:collapse; font-size: large;" cellpadding="10">
            </table>
            </td></tr></table>
        </ContentTemplate>
    </asp:UpdatePanel>
    <br />
    <div id="SSMessage" class="container" style="display:none;">
        <input type="text" id="message" />
        <input type="button" id="sendmessage" value="Send" />
        <input type="hidden" id="HTempGroupID" value="" runat="server" />
        <input type="hidden" id="HUserID" value="" runat="server" />
        <ul id="discussion"></ul>
    </div>
    <iframe id="ifSendMessage" style="display:none" frameborder="0"  runat="server"></iframe>
    <asp:Panel ID="palButtonField" runat="server" HorizontalAlign="Right" ScrollBars="Auto">
        <asp:Button ID="btnBackHomepage" runat="server" CssClass="ORCS_button_control" Text="返回首頁" PostBackUrl="../Homepage/Homepage.aspx" />
    </asp:Panel>
</asp:Content>